version: "2"

services:
  hash-translator:
    build:
      context: hashtranslator-service
    restart: on-failure
    environment:
      HASHTRANSLATOR_HELLO_TEMPLATE: configured hashtranslator hello for %s from %s
    ports:
      - "8099:8099"
  authorization-service:
    build:
      context: authorization-service
    restart: on-failure
    environment:
      AUTHORIZATION_HELLO_TEMPLATE: configured authorization hello for %s from %s
    ports:
      - "8091:8091"
  mongo:
    image: mongo
  postgres:
    image: postgres
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5466:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/

