spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/postgres
#    url: jdbc:postgresql://localhost:5432/auth_service
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
#      mode: never
server:
  port: 8091
#logging:
#  level:
#    root: trace